In [1]:
import warnings
warnings.filterwarnings('ignore')

# MODEL  BUILDING

In [2]:
#Importing basic libraries
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [3]:
#Loading dataset
df=pd.read_csv('cleanchurn.csv',index_col=0)
df

account_length  voice_mail_plan  voice_mail_messages  day_mins  \
0              128.0              1.0                 25.0     265.1   
1              107.0              1.0                 26.0     161.6   
2              137.0              0.0                  0.0     243.4   
3               84.0              0.0                  0.0     299.4   
4               75.0              0.0                  0.0     166.7   
...              ...              ...                  ...       ...   
3328           192.0              1.0                 36.0     156.2   
3329            68.0              0.0                  0.0     231.1   
3330            28.0              0.0                  0.0     180.8   
3331           184.0              0.0                  0.0     213.8   
3332            74.0              1.0                 25.0     234.4   

      evening_mins  night_mins  international_mins  customer_service_calls  \
0           197.40       244.7                10.0                     1.0   
1           195.50       254.4                13.7                     1.0   
2           121.20       162.6                12.2                     0.0   
3            63.55       196.9                 6.6                     2.0   
4           148.30       186.9                10.1                     3.0   
...            ...         ...                 ...                     ...   
3328        215.50       279.1                 9.9                     2.0   
3329        153.40       191.3                 9.6                     3.0   
3330        288.80       191.9                14.1                     2.0   
3331        159.60       139.2                 5.0                     2.0   
3332        265.90       241.4                13.7                     0.0   

      international_plan  day_calls  day_charge  evening_calls  \
0                    0.0      110.0       45.07           99.0   
1                    0.0      123.0       27.47          103.0   
2                    0.0      114.0       41.38          110.0   
3                    0.0       71.0       50.90           88.0   
4                    0.0      113.0       28.34          122.0   
...                  ...        ...         ...            ...   
3328                 0.0       77.0       26.55          126.0   
3329                 0.0       57.0       39.29           55.0   
3330                 0.0      109.0       30.74           58.0   
3331                 0.0      105.0       36.35           84.0   
3332                 0.0      113.0       39.85           82.0   

      evening_charge  night_calls  night_charge  international_calls  \
0              16.78         91.0         11.01                  3.0   
1              16.62        103.0         11.45                  3.0   
2              10.30        104.0          7.32                  5.0   
3               5.40         89.0          8.86                  7.0   
4              12.61        121.0          8.41                  3.0   
...              ...          ...           ...                  ...   
3328           18.32         83.0         12.56                  6.0   
3329           13.04        123.0          8.61                  4.0   
3330           24.55         91.0          8.64                  6.0   
3331           13.57        137.0          6.26                 10.0   
3332           22.60         77.0         10.86                  4.0   

      international_charge  total_charge  churn  
0                     2.70         75.56      0  
1                     3.70         59.24      0  
2                     3.29         62.29      0  
3                     1.78         66.80      0  
4                     2.73         52.09      0  
...                    ...           ...    ...  
3328                  2.67         60.10      0  
3329                  2.59         63.53      0  
3330                  3.81         67.74      0  
3331                  1.35         57.53      

In [4]:
#Divide data into X and Y
X=df.iloc[:,0:18]
Y=df.iloc[:,18]

In [5]:
X

account_length  voice_mail_plan  voice_mail_messages  day_mins  \
0              128.0              1.0                 25.0     265.1   
1              107.0              1.0                 26.0     161.6   
2              137.0              0.0                  0.0     243.4   
3               84.0              0.0                  0.0     299.4   
4               75.0              0.0                  0.0     166.7   
...              ...              ...                  ...       ...   
3328           192.0              1.0                 36.0     156.2   
3329            68.0              0.0                  0.0     231.1   
3330            28.0              0.0                  0.0     180.8   
3331           184.0              0.0                  0.0     213.8   
3332            74.0              1.0                 25.0     234.4   

      evening_mins  night_mins  international_mins  customer_service_calls  \
0           197.40       244.7                10.0                     1.0   
1           195.50       254.4                13.7                     1.0   
2           121.20       162.6                12.2                     0.0   
3            63.55       196.9                 6.6                     2.0   
4           148.30       186.9                10.1                     3.0   
...            ...         ...                 ...                     ...   
3328        215.50       279.1                 9.9                     2.0   
3329        153.40       191.3                 9.6                     3.0   
3330        288.80       191.9                14.1                     2.0   
3331        159.60       139.2                 5.0                     2.0   
3332        265.90       241.4                13.7                     0.0   

      international_plan  day_calls  day_charge  evening_calls  \
0                    0.0      110.0       45.07           99.0   
1                    0.0      123.0       27.47          103.0   
2                    0.0      114.0       41.38          110.0   
3                    0.0       71.0       50.90           88.0   
4                    0.0      113.0       28.34          122.0   
...                  ...        ...         ...            ...   
3328                 0.0       77.0       26.55          126.0   
3329                 0.0       57.0       39.29           55.0   
3330                 0.0      109.0       30.74           58.0   
3331                 0.0      105.0       36.35           84.0   
3332                 0.0      113.0       39.85           82.0   

      evening_charge  night_calls  night_charge  international_calls  \
0              16.78         91.0         11.01                  3.0   
1              16.62        103.0         11.45                  3.0   
2              10.30        104.0          7.32                  5.0   
3               5.40         89.0          8.86                  7.0   
4              12.61        121.0          8.41                  3.0   
...              ...          ...           ...                  ...   
3328           18.32         83.0         12.56                  6.0   
3329           13.04        123.0          8.61                  4.0   
3330           24.55         91.0          8.64                  6.0   
3331           13.57        137.0          6.26                 10.0   
3332           22.60         77.0         10.86                  4.0   

      international_charge  total_charge  
0                     2.70         75.56  
1                     3.70         59.24  
2                     3.29         62.29  
3                     1.78         66.80  
4                     2.73         52.09  
...                    ...           ...  
3328                  2.67         60.10  
3329                  2.59         63.53  
3330                  3.81         67.74  
3331                  1.35         57.53  
3332                  3.70         77.01  

[3333 rows x 18 columns]

In [6]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
3328    0
3329    0
3330    0
3331    0
3332    0
Name: churn, Length: 3333, dtype: int64

# SCALING

In [7]:
#Importing Scaling Libraries
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler

In [8]:
ls=X.columns

In [9]:
ls=ls.values

In [10]:
ls=np.delete(ls,[1,3])

In [11]:
scaler1 =MinMaxScaler().fit(X[ls])
#scaler2 =StandardScaler().fit(X[ls])
#scaler3 =RobustScaler().fit(X[ls])
X1=X
#X2=X
#X3=X
X1[ls]=scaler1.transform(X[ls])
#X2[ls]=scaler2.transform(X[ls])
#X3[ls]=scaler3.transform(X[ls])
Y1=Y.values

In [12]:
#Importing Train test split lib
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2,random_state=5)
x1train,x1test,y1train,y1test=train_test_split(X1,Y1,test_size=0.2,random_state=5)


In [14]:
xtrain

account_length  voice_mail_plan  voice_mail_messages  day_mins  \
1286        0.515815              1.0                 0.28    114.30   
1765        0.535280              0.0                 0.00    132.60   
2961        0.472019              1.0                 0.72    168.00   
1271        0.389294              1.0                 0.74    237.10   
869         0.613139              0.0                 0.00    180.90   
...              ...              ...                  ...       ...   
3190        0.496350              0.0                 0.00    174.70   
3046        0.530414              0.0                 0.00     34.65   
1725        0.476886              0.0                 0.00    128.80   
2254        0.467153              1.0                 0.56    202.30   
2915        0.277372              0.0                 0.00    210.10   

      evening_mins  night_mins  international_mins  customer_service_calls  \
1286      0.495815    0.476391            0.305556                0.285714   
1765      0.573326    0.231881            0.666667                1.000000   
2961      0.362627    0.395864            0.340278                1.000000   
1271      0.730167    0.756772            0.333333                0.285714   
869       0.531114    0.678441            0.298611                0.571429   
...            ...         ...                 ...                     ...   
3190      0.307314    0.379392            0.881944                1.000000   
3046      0.709061    0.164898            0.812500                0.285714   
1725      0.510735    0.798133            0.763889                0.571429   
2254      0.020560    0.706625            0.250000                0.285714   
2915      0.674491    0.344253            0.784722                1.000000   

      international_plan  day_calls  day_charge  evening_calls  \
1286                 0.0   0.791667    0.273867       0.412037   
1765                 0.0   0.726852    0.336772       0.189815   
2961                 0.0   0.319444    0.458536       0.726852   
1271                 0.0   0.273148    0.696197       0.726852   
869                  0.0   0.625000    0.502832       0.662037   
...                  ...        ...         ...            ...   
3190                 0.0   0.967593    0.481594       0.087963   
3046                 0.0   0.421296    0.000000       0.319444   
1725                 0.0   0.365741    0.323827       0.541667   
2254                 0.0   0.467593    0.576456       0.347222   
2915                 0.0   0.736111    0.603358       0.569444   

      evening_charge  night_calls  night_charge  international_calls  \
1286        0.495719     0.250000      0.475977             0.761905   
1765        0.573202     0.509615      0.231678             0.190476   
2961        0.362586     0.692308      0.395358             0.190476   
1271        0.730308     0.692308      0.756922             0.285714   
869         0.531250     0.548077      0.678746             0.380952   
...              ...          ...           ...                  ...   
3190        0.307363     0.586538      0.379072             0.285714   
3046        0.708904     0.250000      0.164088             0.380952   
1725        0.510702     0.798077      0.798453             0.380952   
2254        0.020548     0.153846      0.706433             0.285714   
2915        0.674658     0.384615      0.344055             0.190476   

      international_charge  total_charge  
1286              0.305412      0.283156  
1765              0.666237      0.342021  
2961              0.338918      0.374645  
1271              0.331186      0.813475  
869               0.297680      0.542199  
...                    ...           ...  
3190              0.882732      0.405851  
3046              0.813144      0.050887  
1725              0.764175      0.434929  
2254              0.248711      0.397872  
2915              0.784794      0.650355  

[2666 rows x 18 columns]

In [15]:
ytrain

1286    0
1765    1
2961    1
1271    0
869     0
       ..
3190    1
3046    0
1725    0
2254    0
2915    0
Name: churn, Length: 2666, dtype: int64

In [16]:
xtest

account_length  voice_mail_plan  voice_mail_messages  day_mins  \
1879        0.442822              0.0                 0.00     139.8   
1518        0.501217              0.0                 0.00     139.7   
1813        0.428224              0.0                 0.00     192.1   
890         0.598540              0.0                 0.00     178.4   
1343        0.350365              0.0                 0.00     254.7   
...              ...              ...                  ...       ...   
2641        0.326034              1.0                 0.78     142.0   
1214        0.588808              0.0                 0.00     107.9   
3180        0.437956              0.0                 0.00     151.8   
1328        0.549878              0.0                 0.00     172.0   
54          0.418491              0.0                 0.00     151.0   

      evening_mins  night_mins  international_mins  customer_service_calls  \
1879      0.405204    0.501647            0.437500                0.571429   
1518      0.506004    0.508968            0.569444                0.571429   
1813      0.364083    0.384883            0.208333                0.000000   
890       0.618814    0.420388            0.618056                0.000000   
1343      0.096980    0.325220            0.520833                0.000000   
...            ...         ...                 ...                     ...   
2641      0.647926    0.869143            0.569444                0.285714   
1214      0.626820    0.600476            0.444444                0.571429   
3180      0.145742    0.335835            0.631944                0.285714   
1328      0.774563    0.472731            0.486111                0.285714   
54        0.568231    0.510066            0.458333                1.000000   

      international_plan  day_calls  day_charge  evening_calls  \
1879                 0.0   0.476852    0.361650       0.893519   
1518                 0.0   0.291667    0.361246       0.671296   
1813                 0.0   0.337963    0.541464       0.384259   
890                  0.0   0.236111    0.494337       0.810185   
1343                 0.0   0.310185    0.756675       0.300926   
...                  ...        ...         ...            ...   
2641                 0.0   0.865741    0.369134       0.393519   
1214                 0.0   0.384259    0.251820       0.578704   
3180                 0.0   0.634259    0.402913       0.643519   
1328                 0.0   0.912037    0.472290       0.504630   
54                   0.0   0.337963    0.400081       0.643519   

      evening_charge  night_calls  night_charge  international_calls  \
1879        0.405394     0.836538      0.501221             0.666667   
1518        0.505993     0.519231      0.508550             0.476190   
1813        0.364298     0.865385      0.384772             0.285714   
890         0.619007     0.413462      0.419788             0.190476   
1343        0.097175     0.115385      0.324511             0.761905   
...              ...          ...           ...                  ...   
2641        0.648116     0.230769      0.869300             0.476190   
1214        0.626712     0.682692      0.600570             0.285714   
3180        0.145976     0.365385      0.335098             0.380952   
1328        0.774401     0.500000      0.472720             0.857143   
54          0.568065     0.759615      0.510179             0.285714   

      international_charge  total_charge  
1879              0.436856      0.337234  
1518              0.568299      0.389184  
1813              0.207474      0.436702  
890               0.617268      0.536702  
1343              0.519330      0.523050  
...                    ...           ...  
2641              0.568299      0.533511  
1214              0.444588      0.354787  
3180              0.630155      0.243085  
1328              0.485825      0.584220  
54                0.457474      0.441667  

[667 rows x 18 columns]

In [17]:
ytest

1879    0
1518    0
1813    0
890     0
1343    0
       ..
2641    0
1214    0
3180    0
1328    0
54      1
Name: churn, Length: 667, dtype: int64

In [18]:
#Importing CV searched libraries
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV,StratifiedKFold

In [19]:
cv=StratifiedKFold(n_splits=10,shuffle=True,random_state=24)

In [20]:
#Importing Model Libraries
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import  DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [21]:
# Importing report libraries
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [22]:
#Importing Smote 
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=24)

In [23]:
X_train_smote, y_train_smote = smote.fit_resample(xtrain.astype('float'),ytrain)

In [24]:
y_train_smote.value_counts()

0    2275
1    2275
Name: churn, dtype: int64

In [25]:
X_train_smote

account_length  voice_mail_plan  voice_mail_messages    day_mins  \
0           0.515815         1.000000             0.280000  114.300000   
1           0.535280         0.000000             0.000000  132.600000   
2           0.472019         1.000000             0.720000  168.000000   
3           0.389294         1.000000             0.740000  237.100000   
4           0.613139         0.000000             0.000000  180.900000   
...              ...              ...                  ...         ...   
4545        0.456423         0.000000             0.000000  131.515802   
4546        0.474604         0.489647             0.313374   93.317294   
4547        0.765005         0.000000             0.000000  297.703565   
4548        0.400395         1.000000             0.466868  157.651405   
4549        0.456584         0.000000             0.000000  154.022807   

      evening_mins  night_mins  international_mins  customer_service_calls  \
0         0.495815    0.476391            0.305556                0.285714   
1         0.573326    0.231881            0.666667                1.000000   
2         0.362627    0.395864            0.340278                1.000000   
3         0.730167    0.756772            0.333333                0.285714   
4         0.531114    0.678441            0.298611                0.571429   
...            ...         ...                 ...                     ...   
4545      0.407428    0.476710            0.416732                0.887129   
4546      0.651440    0.369137            0.520165                0.425613   
4547      0.630787    0.646418            0.427189                0.256175   
4548      0.297501    0.767974            0.523037                1.000000   
4549      0.949698    0.799534            0.193884                0.857143   

      international_plan  day_calls  day_charge  evening_calls  \
0                    0.0   0.791667    0.273867       0.412037   
1                    0.0   0.726852    0.336772       0.189815   
2                    0.0   0.319444    0.458536       0.726852   
3                    0.0   0.273148    0.696197       0.726852   
4                    0.0   0.625000    0.502832       0.662037   
...                  ...        ...         ...            ...   
4545                 0.0   0.480259    0.333163       0.726830   
4546                 0.0   0.370275    0.201790       0.710251   
4547                 0.0   0.829050    0.904468       0.569758   
4548                 0.0   0.392998    0.423018       0.170516   
4549                 0.0   0.699074    0.410479       0.377079   

      evening_charge  night_calls  night_charge  international_calls  \
0           0.495719     0.250000      0.475977             0.761905   
1           0.573202     0.509615      0.231678             0.190476   
2           0.362586     0.692308      0.395358             0.190476   
3           0.730308     0.692308      0.756922             0.285714   
4           0.531250     0.548077      0.678746             0.380952   
...              ...          ...           ...                  ...   
4545        0.407536     0.406432      0.476436             0.205526   
4546        0.651619     0.562400      0.368647             0.425613   
4547        0.630848     0.437663      0.646171             0.525422   
4548        0.297594     0.424988      0.768022             0.491203   
4549        0.949575     0.658198      0.799610             0.190476   

      international_charge  total_charge  
0                 0.305412      0.283156  
1                 0.666237      0.342021  
2                 0.338918      0.374645  
3                 0.331186      0.813475  
4                 0.297680      0.542199  
...                    ...           ...  
4545              0.415082      0.306255  
4546              0.519581      0.275909  
4547              0.425288      0.937210  
4548              0.521928      0.410322  
4549              0.191730      0.653534  

[4550

In [26]:
y_train_smote

0       0
1       1
2       1
3       0
4       0
       ..
4545    1
4546    1
4547    1
4548    1
4549    1
Name: churn, Length: 4550, dtype: int64

.

# ML Algorithms

.

#  1 Logistic Regression

In [27]:
model1=LogisticRegression()

# Cross validation score
scores=cross_val_score(model1,xtrain,ytrain,cv=10)
print('Average Cross val score',scores.mean())

# Accuracy Score
model1.fit(xtrain,ytrain)
pred=model1.predict(xtest)
predt=model1.predict(xtrain)
print("Train Model accuracy",accuracy_score(predt,ytrain))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.8608417110191209
Train Model accuracy 0.8608402100525131
Test Model accuracy 0.8725637181409296
[[573  83]
 [  2   9]]
              precision    recall  f1-score   support

           0       1.00      0.87      0.93       656
           1       0.10      0.82      0.17        11

    accuracy                           0.87       667
   macro avg       0.55      0.85      0.55       667
weighted avg       0.98      0.87      0.92       667

Mean Squared Error: 0.12743628185907047
Mean Absolute Error: 0.12743628185907047
Mean Absolute percentage Error: 560417944635309.1


#  Logistic Regression Using Smote dataset

In [28]:
model1=LogisticRegression()

# Cross validation score
scores=cross_val_score(model1,X_train_smote,y_train_smote,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
model1.fit(X_train_smote,y_train_smote)
pred=model1.predict(xtest)
predt=model1.predict(X_train_smote)
print("Train Model accuracy",accuracy_score(predt,y_train_smote))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.6832967032967033
Train Model accuracy 0.6872527472527472
Test Model accuracy 0.6776611694152923
[[381  21]
 [194  71]]
              precision    recall  f1-score   support

           0       0.66      0.95      0.78       402
           1       0.77      0.27      0.40       265

    accuracy                           0.68       667
   macro avg       0.72      0.61      0.59       667
weighted avg       0.71      0.68      0.63       667

Mean Squared Error: 0.32233883058470764
Mean Absolute Error: 0.32233883058470764
Mean Absolute percentage Error: 141792492016162.84


.

# 2.KNN

.

In [29]:
#Finding Best parameters
#model2=KNeighborsClassifier()
#p#aram={'n_neighbors':[3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59]}
#gsc1=GridSearchCV(model2,param,refit=True,cv=cv)
#gsc1.fit(x1train,y1train)
#print("Best parameters for MinMaxScaler Data:",gsc1.best_params_)

In [30]:
#Model Building
model2=KNeighborsClassifier(n_neighbors=9)
print('Min Max Scaler Data Report')
# Cross validation score
scores=cross_val_score(model2,x1train,y1train,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
model2.fit(x1train,y1train)
pred1=model1.predict(x1test)
predt1=model1.predict(x1train)
print("Train Model accuracy",accuracy_score(predt1,y1train))
print('Test Model accuracy',accuracy_score(pred1,y1test))

# Confusion Matrix
print(confusion_matrix(pred1,y1test))

# classification report
print(classification_report(pred1,y1test))

#Error
print("Mean Squared Error:",mean_squared_error(pred1,y1test))
print("Mean Absolute Error:",mean_absolute_error(pred1,y1test))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred1,y1test))

Min Max Scaler Data Report
Average Cross val score 0.8694657993297852
Train Model accuracy 0.6774193548387096
Test Model accuracy 0.6776611694152923
[[381  21]
 [194  71]]
              precision    recall  f1-score   support

           0       0.66      0.95      0.78       402
           1       0.77      0.27      0.40       265

    accuracy                           0.68       667
   macro avg       0.72      0.61      0.59       667
weighted avg       0.71      0.68      0.63       667

Mean Squared Error: 0.32233883058470764
Mean Absolute Error: 0.32233883058470764
Mean Absolute percentage Error: 141792492016162.84


# 3. Support Vector Machine

In [31]:
#Finding Best parameters
#model3=SVC()
#param = [{'kernel':["rbf"],'gamma':[50,5,10,0.5,1,0.001,0.0001,0.00001],'C':[1,15,14,13,12,11,10,0.1] }]
#gsc=GridSearchCV(model3,param,refit=True,cv=cv)
#gsc.fit(xtrain,ytrain)
#print("Best parameters for Data:",gsc.best_params_)


In [32]:
model3=SVC(C=1,gamma=0.5,kernel='rbf')
# Cross validation score
scores=cross_val_score(model3,xtrain,ytrain,cv=10)
print('Average Cross val score',scores.mean())

# Accuracy Score
model3.fit(xtrain,ytrain)
pred=model3.predict(xtest)
predt=model3.predict(xtrain)
print("Train Model accuracy",accuracy_score(predt,ytrain))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.874709245022669
Train Model accuracy 0.8945986496624156
Test Model accuracy 0.881559220389805
[[567  71]
 [  8  21]]
              precision    recall  f1-score   support

           0       0.99      0.89      0.93       638
           1       0.23      0.72      0.35        29

    accuracy                           0.88       667
   macro avg       0.61      0.81      0.64       667
weighted avg       0.95      0.88      0.91       667

Mean Squared Error: 0.1184407796101949
Mean Absolute Error: 0.1184407796101949
Mean Absolute percentage Error: 479393663483216.2


# Support vector machine using smote data

In [33]:
model3=SVC(C=14,gamma=1,kernel='rbf')
# Cross validation score
scores=cross_val_score(model3,X_train_smote,y_train_smote,cv=10)
print('Average Cross val score',scores.mean())

# Accuracy Score
model3.fit(X_train_smote,y_train_smote)
pred=model3.predict(xtest)
predt=model3.predict(X_train_smote)
print("Train Model accuracy",accuracy_score(predt,y_train_smote))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))


Average Cross val score 0.941978021978022
Train Model accuracy 0.9997802197802198
Test Model accuracy 0.8320839580209896
[[516  53]
 [ 59  39]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       569
           1       0.42      0.40      0.41        98

    accuracy                           0.83       667
   macro avg       0.66      0.65      0.66       667
weighted avg       0.83      0.83      0.83       667

Mean Squared Error: 0.1679160419790105
Mean Absolute Error: 0.1679160419790105
Mean Absolute percentage Error: 357857241755076.94


# 4. Decision tree

In [34]:
model4=DecisionTreeClassifier(criterion='gini',min_samples_split=40)
# Cross validation score
scores=cross_val_score(model4,xtrain,ytrain,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
model4.fit(xtrain,ytrain)
pred=model4.predict(xtest)
predt=model4.predict(xtrain)
print("Train Model accuracy",accuracy_score(predt,ytrain))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.9358621272281828
Train Model accuracy 0.9546136534133534
Test Model accuracy 0.9445277361319341
[[562  24]
 [ 13  68]]
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       586
           1       0.74      0.84      0.79        81

    accuracy                           0.94       667
   macro avg       0.86      0.90      0.88       667
weighted avg       0.95      0.94      0.95       667

Mean Squared Error: 0.05547226386806597
Mean Absolute Error: 0.05547226386806597
Mean Absolute percentage Error: 162048562304185.75


# Decision tree using Smote dataset

In [35]:
model4=DecisionTreeClassifier(criterion='entropy',min_samples_split=5)
# Cross validation score
scores=cross_val_score(model4,X_train_smote,y_train_smote,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
model4.fit(X_train_smote,y_train_smote)
pred=model4.predict(xtest)
predt=model4.predict(X_train_smote)
print("Train Model accuracy",accuracy_score(predt,y_train_smote))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.923956043956044
Train Model accuracy 0.9958241758241758
Test Model accuracy 0.8875562218890555
[[519  19]
 [ 56  73]]
              precision    recall  f1-score   support

           0       0.90      0.96      0.93       538
           1       0.79      0.57      0.66       129

    accuracy                           0.89       667
   macro avg       0.85      0.77      0.80       667
weighted avg       0.88      0.89      0.88       667

Mean Squared Error: 0.11244377811094453
Mean Absolute Error: 0.11244377811094453
Mean Absolute percentage Error: 128288445157480.47


# 5. Random Forest

In [36]:
#model5=RandomForestClassifier()
#param={'n_estimators': [130,140,150,160],
 #           'max_samples':[0.8,0.7,0.9],
  #          'max_features': [4,5,6,7,8,9,10,11,12,13,14,15,16],
   #         'random_state':[8,9,10,11,12]}
#rsc=RandomizedSearchCV(model5,param,refit=True,cv=cv,n_iter=50)
#rsc.fit(xtrain,ytrain)
#print("Best parameters for Data:",rsc.best_params_)

In [37]:
final_model=RandomForestClassifier(random_state=9,n_estimators=130,max_samples=0.7,max_features=4)
# Cross validation score
scores=cross_val_score(final_model,xtrain,ytrain,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
final_model.fit(xtrain,ytrain)
pred=final_model.predict(xtest)
predt=final_model.predict(xtrain)
print("Train Model accuracy",accuracy_score(predt,ytrain))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error
print("Mean Squared Error:",mean_squared_error(pred,ytest))
print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))

Average Cross val score 0.9471065303708709
Train Model accuracy 0.9909977494373593
Test Model accuracy 0.95952023988006
[[575  27]
 [  0  65]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       602
           1       0.71      1.00      0.83        65

    accuracy                           0.96       667
   macro avg       0.85      0.98      0.90       667
weighted avg       0.97      0.96      0.96       667

Mean Squared Error: 0.04047976011994003
Mean Absolute Error: 0.04047976011994003
Mean Absolute percentage Error: 182304632592208.97


# Randome Forest for Smote data

In [38]:
#finding best parameters
#model5=RandomForestClassifier()
#param={'n_estimators': [130,140,150,160],
 #           'max_samples':[0.8,0.7,0.9],
  #          'max_features': [4,5,6,7,8,9,10,11,12,13,14,15,16],
   #         'random_state':[8,9,10,11,12]}
#rsc=RandomizedSearchCV(model5,param,refit=True,cv=cv,n_iter=50)#
#rsc.fit(X_train_smote,y_train_smote) 
#print("Best parameters for Data:",rsc.best_params_)

In [39]:
model5=RandomForestClassifier(random_state=11,n_estimators=140,max_samples=0.9,max_features=11)
# Cross validation score
scores=cross_val_score(model5,X_train_smote,y_train_smote,cv=cv)
print('Average Cross val score',scores.mean())

# Accuracy Score
model5.fit(X_train_smote,y_train_smote)
pred=model5.predict(xtest)
predt=model5.predict(X_train_smote)
print("Train Model accuracy",accuracy_score(predt,y_train_smote))
print('Test Model accuracy',accuracy_score(pred,ytest))

# Confusion Matrix
print(confusion_matrix(pred,ytest))

# classification report
print(classification_report(pred,ytest))

#Error

print("Mean Absolute Error:",mean_absolute_error(pred,ytest))
print("Mean Absolute percentage Error:",mean_absolute_percentage_error(pred,ytest))  

Average Cross val score 0.9670329670329669
Train Model accuracy 1.0
Test Model accuracy 0.9535232383808095
[[571  27]
 [  4  65]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       598
           1       0.71      0.94      0.81        69

    accuracy                           0.95       667
   macro avg       0.85      0.95      0.89       667
weighted avg       0.96      0.95      0.96       667

Mean Absolute Error: 0.046476761619190406
Mean Absolute percentage Error: 182304632592208.97


In [40]:
from pickle import dump
from pickle import load

In [41]:
dump(final_model, open('final_model.sav', 'wb'))